### ISSUE TITLE
Fix use of DPoP when testing CSS

### ISSUE THREAD

**Issue by edwardsph** [solid/conformance-test-harness#1]
Using an inrupt broker as the IdP and Bearer tokens, the tests work with CSS.
However, when the access token is DPoP bound we get a 400 response from CSS with the following error:
`Error verifying WebID via DPoP-bound access token...

Is this a problem with the way the token is being bound?

**Comment by RubenVerborgh** [comment]
What's the detail of the error? @matthieubosquet would probably like to know as well.
The detailed error message is coming from https://github.com/solid/identity-token-verifier

**Comment by edwardsph** [comment]
@acoburn and @matthieubosquet helped track it down and Matthieu can fill you in.
