### ISSUE TITLE
Descriptions in Turtle reports

### ISSUE THREAD

**Issue by kjetilk** [solid/conformance-test-harness#141]
I looked through the `report.ttl` file, and noticed it was hard to read, and also took a long time to parse. 

I noted that the `schema:description` predicate contains lengthy excerpts from the spec, and I don't think that's useful, because it retains no document structure, no hypertext, and so I think it made just more difficult. So, just wondering, can we remove those?

**Comment by edwardsph** [comment]
I was wondering about that myself. When we read the RDFa from spec it pulls in a lot of the spec with `schema.org` predicates. Do you think we can just remove anything from this namespace since the CTH reports don't use that namespace themselves?

**Comment by kjetilk** [comment]
Yeah, looking at it, I think we could do that. A link to the spec should suffice, we don't need all those data in the report.

**Comment by edwardsph** [comment]
Resolved by https://github.com/solid/conformance-test-harness/pull/152
